export const BLACK_SPOON_NICKNAMES = [
  "트리플 스타",
  "요리 미치광이",
  "철가방 요리사",
  "만찢남",
  "이모카세",
  "급식 대가",
  "반찬 셰프",
  "영타",
  "히든 천재",
  "간귀",
  "고기 깡패",
  "장사 천재",
  "나폴리 맛피아",
  "딤섬의 여왕",
  "중식 여신",
  "불꽃 남자",
  "키친 갱스터",
  "소스의 제왕",
  "비건 마스터",
  "야식 대마왕",
  "한식 장인",
  "모던 퀴진",
  "파스타 요정",
  "스테이크 킹",
  "해산물 마법사",
  "디저트 왕자",
  "베이커리 퀸",
  "퓨전 전도사",
  "로컬 푸드",
  "캠핑 요리사",
  "편의점 털이범",
  "레시피 도둑",
  "칼질의 신",
  "불맛 감별사",
  "미식 사냥꾼",
  "플레이팅 예술가",
  "가성비 갑",
  "노포 전문가",
  "스트리트 셰프",
  "푸드 트럭",
  "분식 홀릭",
  "야채 소믈리에",
  "향신료 연금술사",
  "육수 장인",
  "면치기 고수",
  "밥도둑 검거반",
  "혼밥 마스터",
  "집밥 선생",
  "도시락 장인",
  "안주 킬러",
];

export const WHITE_SPOON_REAL_NAMES = [
  "최현석",
  "에드워드 리",
  "정지선",
  "여경래",
  "이연복",
  "오세득",
  "박준우",
  "김풍",
  "샘 킴",
  "레이먼 킴",
  "미카엘",
  "강레오",
  "노희영",
  "백종원",
  "안성재",
  "고든 램지",
  "제이미 올리버",
  "피에르 가니에르",
  "알랭 뒤카스",
  "토마스 켈러",
];

export const generateBlackSpoonName = (): string => {
  const index = Math.floor(Math.random() * BLACK_SPOON_NICKNAMES.length);
  return BLACK_SPOON_NICKNAMES[index];
};

export const generateWhiteSpoonName = (): string => {
  const index = Math.floor(Math.random() * WHITE_SPOON_REAL_NAMES.length);
  return WHITE_SPOON_REAL_NAMES[index];
};
